services:
  app:
    build:
      context: .
    container_name: linkraft-server-dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/linkraft?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONT_END_URL: http://localhost:8080
    volumes:
      - .:/usr/src/app:cached
      - linkraft-node_modules:/usr/src/app/node_modules
    command: ['pnpm', 'run', 'start:dev']
    depends_on:
      - postgres
      - redis
    networks:
      - nest-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: linkraft
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - nest-network

volumes:
  postgres-data:
  redis-data:
  linkraft-node_modules:

networks:
  nest-network:
    driver: bridge
